
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://prlehhhkvllfanhmchlc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBybGVoaGhrdmxsZmFuaG1jaGxjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0NDU2MDksImV4cCI6MjA1OTAyMTYwOX0.k5fRNsmWikVEXgl3sXkacBgb_Ft8z3wfFR3MVRflZlI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const options = {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    storageKey: 'websauce_supabase_auth'
  },
  global: {
    headers: {
      'Cache-Control': 'no-store, max-age=0'
    }
  }
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, options);
